### ISSUE TITLE
Add new fields to "Add User Panel"

### ISSUE THREAD

**Issue by ghost** [2c-indore/explore-indore-fe#1]
Hi, I think we must include two new fields in the Add User Panel, 

1. Organization Name
This will help us identify the person through his/her organization, and if at a later stage we plan on giving admin rights to each hospital (to update live count of the number of beds available), they can very well be identified through their organization names. This is a far-sighted suggestion but would be handy if we include it now.

2. Referred By
Similar to the organization name, this is also something, might be helpful in the long-run.

**Comment by arogyakoirala** [comment]
Should the be compulsory, for now I'll make them optional. @devanshjain14

**Comment by arogyakoirala** [comment]
Closing this issue. @devanshjain14 please review changes at exploreindore.klldev.org
