### ISSUE TITLE
Different cases (upper/lower) of the same words on different pages

### ISSUE THREAD

**Issue by ghost** [2c-indore/explore-indore-fe#4]
Example:

When I open details of Apollo Hospital, on the amenities page, the address is

**Scheme No. 74c, Vijay Nagar, Indore**

while

when I try editing this node, the address on the editing page shows the address as, 

**Scheme No. 74C, Vijay Nagar, Indore**

There are many such nodes, where the address has upper and lower case character.

**Comment by arogyakoirala** [comment]
Solved. Need to push changes.

**Comment by arogyakoirala** [comment]
Closing this issue. @devanshjain14 please review changes at exploreindore.klldev.org
